import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white border-b border-slate-200 shadow-sm">
          <div className="max-w-5xl mx-auto px-4 py-2 flex items-center justify-between">
            <Link className="flex items-center gap-3 justify-center" href="/">
              <Image
                src="/img/logo.png"
                alt="Logo"
                width={48}
                height={48}
                className="object-contain"
              />
              <span className="text-xl font-bold tracking-tight text-slate-800 text-center">
                StatusPage
              </span>
            </Link>
            <nav className="flex items-center gap-6">
              <Link
                href="/"
                className="text-slate-600 hover:text-blue-600 transition-colors font-medium"
              >
                Status
              </Link>
              <Link
                href="/about"
                className="text-slate-600 hover:text-blue-600 transition-colors font-medium"
              >
                About
              </Link>
            </nav>
          </div>
        </header>
        {children}
        <footer className="bg-white border-t border-slate-200 shadow-sm mt-8">
          <div className="max-w-5xl mx-auto px-4 py-6 text-center text-slate-600">
            <p className="text-sm">
              © {new Date().getFullYear()} UniProject. All rights reserved.
            </p>
            <p className="text-xs mt-2">
              Powered by{" "}
              <a
                href="https://datadoghq.com"
                className="text-blue-600 hover:underline"
              >
                Datadog
              </a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
